<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsGeoMap\Controller\AdminController'           => __DIR__ . '/src/Controller/AdminController.php',
    'CmsGeoMap\Mapping\AreaInterface'                => __DIR__ . '/src/Mapping/AreaInterface.php',
    'CmsGeoMap\Mapping\GeoImageMappableInterface'    => __DIR__ . '/src/Mapping/GeoImageMappableInterface.php',
    'CmsGeoMap\Mapping\GeoMappableInterface'         => __DIR__ . '/src/Mapping/GeoMappableInterface.php',
    'CmsGeoMap\Mapping\ImageMapInterface'            => __DIR__ . '/src/Mapping/ImageMapInterface.php',
    'CmsGeoMap\Mapping\MapInterface'                 => __DIR__ . '/src/Mapping/MapInterface.php',
    'CmsGeoMap\Mapping\Traits\GeoImageMappableTrait' => __DIR__ . '/src/Mapping/Traits/GeoImageMappableTrait.php',
    'CmsGeoMap\Mapping\Traits\GeoMappableTrait'      => __DIR__ . '/src/Mapping/Traits/GeoMappableTrait.php',
    'CmsGeoMap\Module'                               => __DIR__ . '/src/Module.php',
    'CmsGeoMapTest\Framework\TestCase'               => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsGeoMapTest\SampleTest'                       => __DIR__ . '/tests/SampleTest.php',
);
