<?php
/**
 * CoolMS2 Geo Map Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/geo-map for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsGeoMap;

/*$this->fieldset->setOption('twbs', [
    'col' => ['class' => 'col-xs-12 col-md-8'],
]);

$this->fieldset->get('name')->setOption('twbs', [
    'col' => ['class' => 'col-xs-12 col-md-8 col-md-push-4'],
]);

$this->fieldset->get('description')->setOption('twbs', [
    'col' => ['class' => 'col-xs-12 col-md-8 col-md-push-4'],
]);*/

if ($this->fieldset->has('image') && $this->fieldset->get('image')->getObject()->getId()) {
    $this->fieldset->get('image')->setOption('render_mode', 'static')
        ->setOption('twbs', [
            'element' => [
                'decorators' => [
                    'col' => ['placement' => false],
                ],
            ],
            'label' => ['placement' => false],
            'col' => ['class' => 'col-xs-12 col-md-4'],
            'row' => ['placement' => false],
        ]);
}
?>
<?= $this->formCollection($this->fieldset, true, false);
