<?php
/**
 * CoolMS2 Geo Map Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/geo-map for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsGeoMap;

$this->fieldset->setOption('twbs', [
    'element' => ['type' => 'formControl'],
    'col'     => ['type' => 'formGroupCol', 'class' => 'col-xs-12 col-md-8'],
]);

if ($this->fieldset->has('image') && $this->fieldset->get('image')->getObject()->getId()) {
    $this->fieldset->get('image')->setOption('render_mode', 'static')
        ->setOption('twbs', [
            'element' => [
                'decorators' => [
                    'col' => ['placement' => false],
                ],
            ],
            'label' => ['placement' => false],
            'col' => ['class' => 'col-xs-12 col-md-4'],
            'row' => ['placement' => false],
        ]);
}
?>
<?php if ($this->wrap): ?>
<fieldset data-counter="<?= $this->counter; ?>">
  <?php if ($this->legend): ?><?= $this->legend; ?><?php endif; ?>
<?php endif; ?>
  <?= $this->row([
      $this->formRow($this->fieldset->get('image')),
      $this->formRow($this->fieldset, false, null, false)
  ]); ?>
<?php if ($this->wrap): ?>
</fieldset>
<?php endif;
