<?php
/**
 * CoolMS2 Geo Map Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/geo-map for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsGeoMap;

if ($this->fieldset->has('image') && $this->fieldset->get('image')->getObject()->getId()): ?>
    <?php /*$this->cmsImage($this->fieldset->get('image')->get('id')->getValue(), ['width' => 100]);*/ ?>
<?php
    $this->fieldset->get('image')->setOption('render_mode', 'static');
endif; ?>
    <?= $this->formCollection($this->fieldset, true, false);
